name: divisao_contas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  decimal: ^3.2.4
  provider: ^6.0.0
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_localization: ^0.3.3
  printing: ^5.14.2
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  faker: ^2.2.0

flutter:
  uses-material-design: true
